
import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrea
 */
public class HoroscopeGUI extends javax.swing.JFrame {


    public static void getHoroscope() throws IOException
    {
        //https://www.horoscope.com/us/index.aspx

        
        String webPage = "https://www.horoscope.com/us/index.aspx";
        /*
        Document doc = Jsoup.connect(webPage).get();
        
        Element content = doc.select("div.horoscope-content").first();
        
        String text = content.attr("");
        
        System.out.println(text);
        */
        /*
        String stuff = Jsoup.connect(webPage).get().html();
        Document doc = Jsoup.parse(stuff);
        Element p= doc.select("p").first();
        String text = p.text();
        */
    }

    /**
     * Creates new form HoroscopeGUI
     */
    public HoroscopeGUI() {
        initComponents();
        //centers form in screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbSign = new javax.swing.JComboBox<>();
        btnHoroscope = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select your sign:");

        cmbSign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aquarius", "Pisces", "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn" }));
        cmbSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSignActionPerformed(evt);
            }
        });

        btnHoroscope.setText("Get Horoscope");
        btnHoroscope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoroscopeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSign, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnHoroscope)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHoroscope)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoroscopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoroscopeActionPerformed

        try {
            getHoroscope();
        }catch(IOException ex)
        {
            Logger.getLogger(HoroscopeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

            /*String sign = cmbSign.getSelectedItem().toString();

            switch (sign) {
            //TODO implement the rest of the signs
            //TODO implement API
            case "Pisces":
            JOptionPane.showMessageDialog(null, "Tension between you and a business partner could "
            + "have you doubting \nyour professional future in the current situation. Don't "
            + "\nwaste too much time worrying about it. You may not be aware of it now, but "
            + "\ncareer and money matters are going well and are likely to continue like this "
            + "\nfor a while. Of course, that depends on you and what you're willing to do to "
            + "\nkeep it going.", sign + " Horoscope", JOptionPane.PLAIN_MESSAGE);
            }

            */

    }//GEN-LAST:event_btnHoroscopeActionPerformed

    private void cmbSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoroscopeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoroscopeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoroscopeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoroscopeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoroscopeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoroscope;
    private javax.swing.JComboBox<String> cmbSign;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
